{
gROOT->ProcessLine(".L /a/home/tehanu/omw2107/classes/vegasAnalysis.cpp");
vector <float> bin;
vector <float> res;
vector <float> rms;
int bins = 10;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_000wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 000;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_000wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_025wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 025;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_025wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_050wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 050;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_050wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_075wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 075;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_075wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_100wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 100;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_100wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_125wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 125;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_125wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_150wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 150;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_150wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_175wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 175;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_175wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=20;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=20;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_20deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=45;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=45;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_45deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=50;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=50;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_50deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=55;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=55;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_55deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=60;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=60;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_60deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=65;
int noises=350;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_200wobb_350noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;

char epo='na';
int epochs = 6;
int wobbles = 200;
int atms=21;
int Zeniths=65;
int noises=400;
vegasAnalysis *v = new vegasAnalysis("/a/home/tehanu/dribeiro/Analysis/CrabSim/runlists/Classes//Oct2012_na_ATM21_vegasv250rc5_7samples_65deg_200wobb_400noise-med-com-geo.txt",999999);
v->getBinnedResolution(bin, res, rms, "fEnergy_GeV", 0, bins,"Logarithmic");
cout << "DATATATA"<< endl;
for(int i=0;i<bins;i++) cout << epo << " " << atms << " " << Zeniths << " " <<  wobbles << " " <<  noises << " " <<  bin[i] << " " << res[i] << " " <<  rms[i] <<  endl;
}
